source 'https://rubygems.org'

ruby '3.3.0'

gem 'bootsnap', require: false
gem 'kaminari'
gem 'pg', '~> 1.1'
gem 'puma', '>= 6.0'
gem 'rack-cors'
gem 'rails', '~> 8.0.0'
gem 'tzinfo-data', platforms: %i[mswin mswin64 mingw x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'shoulda-matchers'
end
